environments:
  production:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: mongodb
    namespace: registrar-v2
    chart: bitnami/mongodb
    version: 10.1.2
    values:
      - ./config/mongodb.yaml.gotmpl
